/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CombatStats = IDL.Record({
  'hitPoints' : IDL.Nat,
  'speed' : IDL.Nat,
  'hitDice' : IDL.Text,
  'baseArmorClass' : IDL.Nat,
  'initiative' : IDL.Int,
});
export const Item = IDL.Record({
  'weight' : IDL.Opt(IDL.Float64),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const AbilityScores = IDL.Record({
  'dexterity' : IDL.Nat,
  'wisdom' : IDL.Nat,
  'strength' : IDL.Nat,
  'charisma' : IDL.Nat,
  'constitution' : IDL.Nat,
  'intelligence' : IDL.Nat,
});
export const Skill = IDL.Record({
  'modifier' : IDL.Int,
  'name' : IDL.Text,
  'associatedAbility' : IDL.Text,
  'isProficient' : IDL.Bool,
});
export const CharacterSheet = IDL.Record({
  'combatStats' : CombatStats,
  'inventory' : IDL.Vec(Item),
  'abilities' : AbilityScores,
  'skills' : IDL.Vec(Skill),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllSheets' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, CharacterSheet))],
      ['query'],
    ),
  'getAllSnapshots' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Tuple(IDL.Text, CharacterSheet)))
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSnapshotDates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCharacterSheetSaved' : IDL.Func([], [IDL.Bool], ['query']),
  'loadSheet' : IDL.Func([], [CharacterSheet], ['query']),
  'loadSnapshot' : IDL.Func([IDL.Text], [IDL.Opt(CharacterSheet)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSheet' : IDL.Func([CharacterSheet], [], []),
  'saveSnapshot' : IDL.Func([IDL.Text, CharacterSheet], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CombatStats = IDL.Record({
    'hitPoints' : IDL.Nat,
    'speed' : IDL.Nat,
    'hitDice' : IDL.Text,
    'baseArmorClass' : IDL.Nat,
    'initiative' : IDL.Int,
  });
  const Item = IDL.Record({
    'weight' : IDL.Opt(IDL.Float64),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const AbilityScores = IDL.Record({
    'dexterity' : IDL.Nat,
    'wisdom' : IDL.Nat,
    'strength' : IDL.Nat,
    'charisma' : IDL.Nat,
    'constitution' : IDL.Nat,
    'intelligence' : IDL.Nat,
  });
  const Skill = IDL.Record({
    'modifier' : IDL.Int,
    'name' : IDL.Text,
    'associatedAbility' : IDL.Text,
    'isProficient' : IDL.Bool,
  });
  const CharacterSheet = IDL.Record({
    'combatStats' : CombatStats,
    'inventory' : IDL.Vec(Item),
    'abilities' : AbilityScores,
    'skills' : IDL.Vec(Skill),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllSheets' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, CharacterSheet))],
        ['query'],
      ),
    'getAllSnapshots' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Principal,
              IDL.Vec(IDL.Tuple(IDL.Text, CharacterSheet)),
            )
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSnapshotDates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCharacterSheetSaved' : IDL.Func([], [IDL.Bool], ['query']),
    'loadSheet' : IDL.Func([], [CharacterSheet], ['query']),
    'loadSnapshot' : IDL.Func([IDL.Text], [IDL.Opt(CharacterSheet)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSheet' : IDL.Func([CharacterSheet], [], []),
    'saveSnapshot' : IDL.Func([IDL.Text, CharacterSheet], [], []),
  });
};

export const init = ({ IDL }) => { return []; };