/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AbilityScores {
  'dexterity' : bigint,
  'wisdom' : bigint,
  'strength' : bigint,
  'charisma' : bigint,
  'constitution' : bigint,
  'intelligence' : bigint,
}
export interface CharacterSheet {
  'combatStats' : CombatStats,
  'inventory' : Array<Item>,
  'abilities' : AbilityScores,
  'skills' : Array<Skill>,
}
export interface CombatStats {
  'hitPoints' : bigint,
  'speed' : bigint,
  'hitDice' : string,
  'baseArmorClass' : bigint,
  'initiative' : bigint,
}
export interface Item {
  'weight' : [] | [number],
  'name' : string,
  'description' : string,
  'quantity' : bigint,
}
export interface Skill {
  'modifier' : bigint,
  'name' : string,
  'associatedAbility' : string,
  'isProficient' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllSheets' : ActorMethod<[], Array<[Principal, CharacterSheet]>>,
  'getAllSnapshots' : ActorMethod<
    [],
    Array<[Principal, Array<[string, CharacterSheet]>]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSnapshotDates' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCharacterSheetSaved' : ActorMethod<[], boolean>,
  'loadSheet' : ActorMethod<[], CharacterSheet>,
  'loadSnapshot' : ActorMethod<[string], [] | [CharacterSheet]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSheet' : ActorMethod<[CharacterSheet], undefined>,
  'saveSnapshot' : ActorMethod<[string, CharacterSheet], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];